[tool.poetry]
name = "mmhdan"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.6.0"
fastapi = "^0.62.0"
fastapi-utils = "^0.2.1"
gunicorn = "^20.0.4"
loguru = "^0.5.3"
mmh3 = "^2.5.1"
requests = "^2.25.0"
uvicorn = {extras = ["standard"], version = "^0.12.3"}

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autopep8 = "^1.5.4"
black = "^20.8b1"
coveralls = "^2.2.0"
flake8 = "^3.8.4"
isort = "^5.6.4"
mypy = "^0.790"
pre-commit = "^2.9.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
pytest-randomly = "^3.5.0"
pytest-sugar = "^0.9.4"
pyupgrade = "^2.7.4"
vcrpy = "^4.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
