[tool.poetry]
name = "mmhdan"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.5.0"
fastapi = "^0.61.1"
fastapi-utils = "^0.2.1"
gunicorn = "^20.0.4"
loguru = "^0.5.3"
mmh3 = "^2.5.1"
requests = "^2.24.0"
uvicorn = "^0.12.1"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autopep8 = "^1.5.4"
black = "^20.8b1"
coveralls = "^2.1.2"
flake8 = "^3.8.3"
isort = "^5.5.4"
mypy = "^0.782"
pre-commit = "^2.7.1"
pytest = "^6.1.0"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
pytest-randomly = "^3.4.1"
pytest-sugar = "^0.9.4"
pyupgrade = "^2.7.2"
vcrpy = "^4.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
