[tool.poetry]
name = "mmhdan"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiodns = "^3.0.0"
aiofiles = "^0.8.0"
asyncwhois = "^1.0.0"
beautifulsoup4 = "^4.11.1"
d8s-urls = "^0.6.0"
fastapi = "^0.79.0"
fastapi-utils = "^0.2.1"
gunicorn = "^20.1.0"
ioc-finder = "^7.2.3"
loguru = "^0.6.0"
mmh3 = "^3.0.0"
pyOpenSSL = "^22.0.0"
requests = {extras = ["security"], version = "^2.28.1"}
tldextract = "^3.3.1"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
whois-parser = "^0.1.4"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autopep8 = "^1.6.0"
black = "^22.6.0"
coveralls = "^3.3.1"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.971"
pre-commit = "^2.20.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.5"
pyupgrade = "^2.37.3"
vcrpy = "^4.2.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
